name: Backup

on:
  push:
    # branches:
    #   - main
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * * # Every day of each month

permissions:
  contents: read

jobs:
  call_sync_to_aws:
    uses: exercism/github-actions/.github/workflows/backup-repo.yml@backup-repo
    secrets: inherit
